/**
 ******************************************************************************
 * @file    main.c
 * @author  Auto-generated by STM32CubeIDE
 * @version V1.0
 * @brief   Default main function.
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include "main.h"

void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

void init_systick_timer(uint32_t);
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack);
void init_task_stack(void);
void enable_processor_faults(void);
__attribute__((naked)) void switch_sp_to_psp(void);
void save_psp_value(uint32_t);
void update_next_task(void);

void delay(uint32_t);

int main(void) {

	enable_processor_faults();

	//set MSP of the scheduler
	init_scheduler_stack(SCHED_STACK_START);

	//set task's stack with dummy stack frames
	init_task_stack();

	//1ms tick
	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

	for (;;)
		;
}

void task1_handler(void) {
	while (1) {
		printf("Green ON\n");
		delay(DELAY_COUNT_1S);
		printf("Green OFF\n");
		delay(DELAY_COUNT_1S);

	}
}

void task2_handler(void) {
	while (1) {
		printf("Orange ON\n");
		delay(DELAY_COUNT_500MS);
		printf("Orange OFF\n");
		delay(DELAY_COUNT_500MS);
	}
}

void task3_handler(void) {
	while (1) {
		printf("Blue ON\n");
		delay(DELAY_COUNT_250MS);
		printf("Blue ON\n");
		delay(DELAY_COUNT_250MS);
	}
}

void task4_handler(void) {
	while (1) {
		printf("Red ON\n");
		delay(DELAY_COUNT_125MS);
		printf("Red OFF\n");
		delay(DELAY_COUNT_125MS);
	}
}

void init_systick_timer(uint32_t tick_hz) {

	uint32_t *pSRVR = (uint32_t*) 0xE000E014; //SysTick Reload Value Register
	uint32_t *pSCSR = (uint32_t*) 0xE000E010; //SysTick Control and Status Register

	uint32_t count_value = SYSTICK_TIM_CLK / tick_hz - 1;

	//clear n load the value into SVR
	*pSRVR = ~(0x00FFFFFF);
	*pSRVR |= count_value;

	*pSCSR |= (1 << 1); //Enables SysTick exception request
	*pSCSR |= (1 << 2); //clock source = processor clock

	*pSCSR |= (1 << 0); //enable systick

}


void delay(uint32_t count) {
	for (uint32_t i = 0; i < count; i++)
		;
}

__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack) {
	__asm volatile ("MSR MSP,R0");
	//Put the first argument (AAPCS)ie. sched_top_of_stack into MSP
	//Return from this sub routine. as this is a naked function there is no epilogue/prologue sequences for this function call
	__asm volatile("BX LR");
}

//uint32_t psp_of_tasks[MAX_TASKS] = { T1_STACK_START, T2_STACK_START,
//T3_STACK_START, T4_STACK_START };
//
//uint32_t task_handlers[MAX_TASKS] = { (uint32_t) task1_handler,
//		(uint32_t) task2_handler, (uint32_t) task3_handler,
//		(uint32_t) task4_handler };

typedef struct {
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void (*task_handler)(void);
} TCB_t;

TCB_t user_tasks[MAX_TASKS];

void init_task_stack(void) {

	user_tasks[0].current_state = TASK_RUNNING_STATE;
	user_tasks[1].current_state = TASK_RUNNING_STATE;
	user_tasks[2].current_state = TASK_RUNNING_STATE;
	user_tasks[3].current_state = TASK_RUNNING_STATE;

	user_tasks[0].psp_value = T1_STACK_START;
	user_tasks[1].psp_value = T2_STACK_START;
	user_tasks[2].psp_value = T3_STACK_START;
	user_tasks[3].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = task1_handler;
	user_tasks[1].task_handler = task2_handler;
	user_tasks[2].task_handler = task3_handler;
	user_tasks[3].task_handler = task4_handler;

	uint32_t *pPSP;

	for (int i = 0; i < MAX_TASKS; i++) {
		(pPSP) = (uint32_t*) user_tasks[i].psp_value;//make this pointer point to TOS of task and start fill with dummy values.this is odd.
//<-
		pPSP--;
		*pPSP = DUMMY_XPSPR;	//(1<<24) - T bit=1

		pPSP--;
		*pPSP = (uint32_t)user_tasks[i].task_handler;	//PC

		pPSP--;
		*pPSP = 0xFFFFFFFD;	//LR-return to thread mode,use PSP,no FPU

		//R0-R12
		for (int j = 0; j < 13; j++) {
			pPSP--;
			*pPSP = 0;
		}
		user_tasks[i].psp_value = (uint32_t) pPSP;

	}
}

void enable_processor_faults(void) {

	uint32_t *pSHCSR = (uint32_t*) 0xE000ED24;

	*pSHCSR |= (1 << 16); //mem manage
	*pSHCSR |= (1 << 17); //bus fault
	*pSHCSR |= (1 << 18); //usage fault

}

uint8_t current_task = 0; //task 1
uint32_t get_psp_value(void) {
	return user_tasks[current_task].psp_value; //return value stored in R0 (AAPCS)
}

__attribute__((naked)) void switch_sp_to_psp(void) {
	//init the psp with task1 stack start
	__asm volatile ("PUSH {LR}");
	//saving this to MSP as we are about to use LR
	__asm volatile ("BL get_psp_value");
	//using BL not only B as we have to return back
	__asm volatile ("MSR PSP,R0");
	//return value stored into PSP
	__asm volatile ("POP {LR}");

	//change SP to PSP
	__asm volatile("MOV R0,#0x02");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile("BX LR");

}

void save_psp_value(uint32_t current_psp) {
	user_tasks[current_task].psp_value = current_psp;
}

void update_next_task(void) {
	//round robin
	current_task++;
	current_task %= MAX_TASKS; //0-3
}

__attribute__((naked)) void SysTick_Handler(void) {
	//save the context of current task
	__asm volatile ("MRS R0,PSP");
	//store r4-r11, cant use push as this is handler code and MSP is used
	__asm volatile ("STMDB R0!,{R4-R11}");

	__asm volatile("PUSH {LR}");

	__asm volatile ("BL save_psp_value");

	//retrieve context of next task
	__asm volatile ("BL update_next_task");
	//get psp value of the next task
	__asm volatile ("BL get_psp_value");
	//retrieve r4-r11 of this task

	__asm volatile ("LDM R0!,{R4-R11}");
	// <-
	//update psp
	__asm volatile("MSR PSP,R0");

	__asm volatile("POP {LR}");
	//EXEC_RETURN copied into PC and exit sequence is triggered.
	__asm volatile("BX LR");

}

void HardFault_Handler(void) {
	printf("Exception : Hardfault\n");
	while (1)
		;
}

void MemManage_Handler(void) {
	printf("Exception : MemManage\n");
	while (1)
		;
}

void BusFault_Handler(void) {
	printf("Exception : BusFault\n");
	while (1)
		;
}
